language: java
cache:
  directories:
    - "$HOME/.cache"

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.ms/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true